[workspace]

members = [
  "rolldice",
  "tftp",
  "shell",
  "ebml",
  "game-server",
  "clog",
  "web-server",
  "programming-wisdom",
  "hyper-app",
  "plum",
  "file-transfer",
  "count-words",
  "calculator",
  "socks5", "markdown-viewer",
]
