[package]
name = "rolldice"
version = "0.1.0"
authors = ["Patrick Tsai <patrick@simplypatrick.com>"]
edition = "2018"

[dependencies]
rand = "0.8.5"
structopt = "0.3.26" # Note: structopt is now in maintenance mode. Consider migrating to clap 4.x directly in the future.
